#version: "3.9"

services:

  mysql:
    image: mariadb:10.11
    #container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    command:
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --server-id=1
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-prootpass"]
      interval: 10s
      retries: 10

  postgres:
    image: postgres:15
    #container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 10

  pgchameleon:
    image: the4thdoctor/pgchameleon:latest
    #container_name: pgchameleon
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./pgchameleon/config.yml:/etc/pgchameleon/config.yml
      - ./sysdata/pgcham-data:/var/lib/pgchameleon
    command: >
      bash -c "
      chameleon setconf replica1 &&
      chameleon create_replica replica1 &&
      chameleon start_replica replica1 &&
      tail -f /var/lib/pgchameleon/logs/*.log
      "

volumes:
  mysql-data:
  pg-data:
  pgcham-data:
