
services:

  dbm:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: delphis
      MYSQL_USER: musr
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - "23306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --binlog-format=ROW --server-id=1 --log-bin=mysql-bin --binlog-row-image=FULL --expire_logs_days=10 --binlog_row_metadata=FULL
    networks:
      - default
    healthcheck:
       test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost", "--password=${MYSQL_ROOT_PASSWORD}"]
       interval: 120s
       timeout: 15s
       retries: 5
       start_period: 40s
      
  pg:
    # image: postgres:15
    build: 
      context: ./
      dockerfile: Dockerfile.pg
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    env_file:
      - .env
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 120s
      timeout: 20s
      retries: 5
      start_period: 40s

  chameleon:
    build: .
    restart: always
    volumes:
      - ./pg_chameleon_volume:/dg:ro
      - ./config:/home/chameleon/.pg_chameleon/configuration
      - chameleon_logs:/var/log/pg_chameleon
    networks:
      - default
    stdin_open: true
    tty: true
    env_file:
      - .env
    #command: tail -f /dev/null
    command:  bash /dg/startpgcham.sh
    depends_on:
      dbm:
        condition: service_healthy
      pg:
        condition: service_healthy

  adminer:
    # http://10.33.44.81:6607/  use dbm or ip:port for server while logging in. 192.168.88.60:6608
    image: adminer:5
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
    env_file:
      - .env
    environment:
      - ADMINER_DEFAULT_SERVER=pg
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
      - ADMINER_PLUGINS=tables-filter
    ports:
      - 6607:8080
    networks:
      - default

volumes:
  mysql_data:
  postgres_data:
  chameleon_logs:


