
services:

  wallabag:
    # http://10.33.44.81:8087/ 
    image: wallabag/wallabag:2.6.13
    restart: unless-stopped
    env_file:
      - .env.wala
    environment:
      # - MYSQL_ROOT_PASSWORD=
      # - SYMFONY__ENV__DATABASE_PASSWORD=
      # - SYMFONY__ENV__FROM_EMAIL=
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_TABLE_PREFIX="wallabag_"
    ports:
      - "8087:80"
    volumes:
      # I got dir not exists errors with this...
      # - ../sysdata/waladata:/var/www/wallabag
      # works ok..
      # - waladata:/var/www/wallabag
      - /etc/localtime:/etc/localtime:ro
      - ../sysdata/wallabag_img/images:/var/www/wallabag/web/assets/images
    depends_on:
      dbm:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
       - default
       - cfnet_red74dgwin

  dbm:
    image: mariadb:12
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # - MYSQL_ROOT_PASSWORD=
      - x33=x33
    volumes:
      #- db_data:/var/lib/mysql # 2026-01-25 switch to bind mount
      - ../sysdata/mysqldata:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--innodb_initialized"]
      interval: 20s
      timeout: 3s
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"
    networks:
       - default

  redis:
    image: redis:alpine
    restart: unless-stopped    
    volumes:
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"
    networks:
       - default

  adminer:
    # http://10.33.44.81:6613/  use dbm or ip:port for server while logging in.
    image: adminer:5.3.0
    restart: unless-stopped
    ports:
      - 6613:8080
    # env_file:
      # - .env
    environment:
      - ADMINER_DEFAULT_SERVER=dbm
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"
    networks:
       - default

volumes:
  waladata:
  wala_img:
  db_data:
    
networks:
  cfnet_red74dgwin:
    external: true
   
