# Generated by Django 4.1.7 on 2023-07-27 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogappm2m', '0002_alter_posttbl_postedfrom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttbl',
            name='postedfrom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postedfrom', to='blogappm2m.postedfromtbl'),
        ),
    ]
