version: "3"
    
volumes:
  pordata:

services:

  portainer:
    # https://192.168.88.69:9443/  
    restart: always
    image: portainer/portainer-ce:latest
    ports:
      - 2123:9443
    volumes:
      - pordata:/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env

# portainer container link opens to 0.0.0.0
# https://www.reddit.com/r/portainer/comments/y4tt7s/0000_ip_address_for_container_ui/
# https://portal.portainer.io/knowledge/exposed-ports-in-the-container-view-redirect-me-to-0.0.0.0-what-can-i-do
# Change the configuration of your Docker daemon by adding the --ip option.
# no:    command: --ip=${host_ip}


  # jupyterlab
  # https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html
  jplab:
    # http://10.4.1.231:18888  lab?token=   930f63f2611d3db4ecaaab02e60a6e28129564a566b7445a
    # http://10.4.1.231:18889/lab?token=8614e1f8690bbcd825255cb2332e477c057e3854bd63d573
    # http://192.168.88.69:2123/
    image: quay.io/jupyter/base-notebook:2023-10-31
    ports:
      - "2123:8888"
      # - "18000:8000"
    # working_dir: /home/jovyan
    env_file:
      - ./.env
    volumes:
      # - ./data/jlab:/home/jovyan/work
      - /ap:/home/jovyan/work
      - /etc/localtime:/etc/localtime:ro
    # entrypoint: bash -c 'jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/home --allow-root'
    command: start-notebook.py --ServerApp.root_dir=/home/jovyan/work
    restart: always
    user: root  

  wetty:
    # ref:  https://github.com/butlerx/wetty/blob/main/docker-compose.yml   
    # https://butlerx.github.io/wetty/#/atoz    https://github.com/butlerx/wetty
    # http://192.168.88.69:2124/wetty
    image: wettyoss/wetty
    tty: true
    working_dir: /usr/src/app
    restart: always
    ports:
      - '2124:3000'
    command: wetty --ssh-host 192.168.88.69 --ssh-port 22  --title ".168.88.69" 


  # gotty:
    # # http://192.168.88.69:16412/
    # build:
      # context: "./gotty"
      # dockerfile: Dockerfile
    # # working_dir: /code
    # # --credential a:1325 (user:pass) . 
    # command: gotty -w --credential a:1325  bash
    # ports:
      # - "16412:8080"
    # env_file:
      # - ./.env

