# Generated by Django 4.1.7 on 2023-10-30 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.CharField(max_length=100)),
                ('rank', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompactIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('rank', models.IntegerField(max_length=500)),
                ('issues', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attach_photo_of_rid', models.ImageField(upload_to='upload/images/')),
                ('attempts_to_fix', models.TextField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('reason_for_deviation', models.TextField(max_length=500)),
                ('sign_off', models.CharField(max_length=500)),
                ('attach_photo_of_cmm', models.ImageField(upload_to='upload/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Engineering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_analysis', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('prevent_recurrence', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=500)),
                ('part_number', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurance', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('press_position', models.CharField(max_length=500)),
                ('rig_num', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tonnage', models.CharField(max_length=500)),
                ('fault_msg', models.CharField(max_length=500)),
                ('head_num', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PressSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('press_num', models.BigIntegerField()),
                ('process', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_email', models.CharField(max_length=500)),
                ('supervisors', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('serial_num', models.CharField(max_length=500)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fix', models.CharField(max_length=500)),
                ('tool_num', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolsShopFloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('tool_num', models.CharField(max_length=500)),
                ('serial_num', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ToolRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('observations_breakdown', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broken_part_pic_tr', models.ImageField(upload_to='upload/images/')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbreakapp624c.tool')),
            ],
        ),
        migrations.CreateModel(
            name='ToolBreakageReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('if_other_describe', models.TextField(max_length=500)),
                ('countermeasure', models.TextField(max_length=500)),
                ('sup_approval', models.CharField(max_length=500)),
                ('break_dev_select', models.CharField(max_length=500)),
                ('broken_part_pic', models.ImageField(upload_to='upload/images/')),
                ('status', models.CharField(max_length=500)),
                ('num_parts_before_breakage', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_name', models.CharField(max_length=500)),
                ('root_cause', models.TextField(max_length=500)),
                ('report_date_time', models.DateTimeField()),
                ('broken_tools_shop_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbreakapp624c.toolsshopfloor')),
                ('coining_issue', models.ManyToManyField(to='toolbreakapp624c.coinissue')),
                ('compact_issue', models.ManyToManyField(to='toolbreakapp624c.compactissue')),
                ('engineering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbreakapp624c.engineering')),
                ('part_number', models.ManyToManyField(to='toolbreakapp624c.partnumber')),
                ('press_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbreakapp624c.pressinfo')),
                ('press_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbreakapp624c.pressselect')),
                ('toolroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbreakapp624c.toolroom')),
            ],
        ),
    ]
