# Generated by Django 4.1.7 on 2023-10-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogappm2m', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttbl',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='upload/images/'),
        ),
    ]
