
# https://hub.docker.com/r/openhab/openhab/#running-from-compose-fileyml
# http://192.168.88.77:8080

version: "3.6"

services:
  openhab:
    image: "openhab/openhab:4.1.2"
    restart: always
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./sysdata/openhab_addons:/openhab/addons"
      - "./sysdata/openhab_conf:/openhab/conf"
      - "./sysdata/openhab_userdata:/openhab/userdata"
    environment:
      CRYPTO_POLICY: "unlimited"
      EXTRA_JAVA_OPTS: "-Duser.timezone=America/Toronto"
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"

