
services:

  wallabag:
    # http://10.33.44.81:8087/
    image: wallabag/wallabag:2.6.13
    restart: unless-stopped
    ports:
      - "8087:80"
    environment:
      - SYMFONY__ENV__DATABASE_TABLE_PREFIX="wallabag_"
    depends_on:
      dbm:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.wala
    volumes:
      # - /opt/wallabag/images:/var/www/wallabag/web/assets/images
      - waladata:/var/www/wallabag
    # this gets error, see status to run it once....
    #command:  sh -c "    bin/console doctrine:migrations:migrate --no-interaction --env=prod && php-fpm "
      
  dbm:
    image: mariadb:12
    restart: unless-stopped
    env_file:
      - .env
    #command: --innodb-file-per-table=1 --default-authentication-plugin=mysql_native_password  --secure_file_priv=/crib
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # folder for mysql's internal data files.
      # - ../sysdata/mysqldata:/var/lib/mysql/  
      - db_data:/var/lib/mysql/  
      # - ./script:/script
      # folders for imported or exported data, etc.
      # - ../sysdata/in-out/:/in-out
      # - ../data/crib/:/crib
      # - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"
    # networks:
      # # - sister
      # # - sister2
      # - basenet1
      # - cfnet1
      # #- sister3
    healthcheck:
       test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost", "--password=${MYSQL_ROOT_PASSWORD}"]
       interval: 120s
       timeout: 15s
       retries: 5
       start_period: 240s
       
  redis:
    image: redis:alpine
    restart: unless-stopped    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s

    
  adminer:
    # http://10.33.44.81:6613/  use dbm or ip:port for server while logging in.
    image: adminer:5.3.0
    restart: unless-stopped
    ports:
      - 6613:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # the rustpad db is in: /ap/dkr/dkrcollection617a/rustpad14/sysdata/paddata
      #- ../../rustpad14/sysdata/paddata:/rpad
      #- ./docker-adminer/sqlite.php:/var/www/html/sqlite.php  # Mount your custom PHP entrypoint
      #- ./docker-adminer/plugins/login-password-less.php:/var/www/html/plugins/login-password-less.php
      #- ./docker-adminer/plugins-enabled/login-password-less.php:/var/www/html/plugins-enabled/login-password-less.php
      #- ./djangosite/db.sqlite3:/db.sq3
      #- ./adminer-sqlite:/var/www/html
    env_file:
      - .env
    environment:
      - ADMINER_DEFAULT_SERVER=dbm
      # - ADMINER_PLUGINS=login-password-less
      # - ADMINER_PLUGINS='tables-filter tinymce'
      # - ADMINER_DEFAULT_SERVER=srvr
      # - DB_PATH=/rpad/rustpad.db
      # - DB_USER=user
      # - DB_PASS=apass
    # networks:
      # # - sister
      # - basenet1
      # - cfnet1
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"


volumes:
  waladata:
  db_data:
 
networks:
  sister:
    name: sister
  sister2:
    #external: true
    name: sister2
  basenet1:
    name: basenet1
  cfnet1:
    #external: true
    name: cfnet1
  # sister4:
    # name: sister4
    
    