
networks:
  # sister2:
    # name: sister2
    # external: true
  cfnet_r74_daveg2online:
    name: cfnet_r74_daveg2online
  #cfnet1:
    # phase next line out..
    # name: cfnet1

services:

  # Cloudflare Tunnel Container
  cftunnel:
    image: cloudflare/cloudflared
    command: tunnel  --no-autoupdate  run  --token ${TUNNEL_TOKEN}
    # in token mode, volumes are ignored. Volumes are used in named tunnel mode.
    # volumes:
      # - ./sysdata/cflared:/etc/cloudflared
    restart: unless-stopped
    environment:
      # TUNNEL_TOKEN: ${TUNNEL_TOKEN} 
      - TZ=America/New_York # Adjust to your timezone
    user:  root
    networks:
      - cfnet_r74_daveg2online
