# Generated by Django 4.1.7 on 2024-12-16 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveyapp', '0012_remove_answer_comment_by_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='answer',
            name='active_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='answer',
            name='sort_order',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='active_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='sort_order',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='active_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='survey',
            name='sort_order',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
