# Generated by Django 4.1.7 on 2024-12-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0013_rename_submitted_at_answer_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='choice_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_tbl_grouping', models.CharField(max_length=100)),
                ('choice_name', models.CharField(max_length=100)),
            ],
        ),
    ]
