#
# /am/cruc4tb/koofry/volums/seafileall/sflarge/sysdata/bakup/ubu398e-redek446code/srv/dkr/422dkrcol/nextcloud455

services:

  nc:
    # http://192.168.88.103:6219
    image: nextcloud:apache
    restart: always
    ports:
      - 6219:80
    env_file:
      - .env
    volumes:
      - nc_data:/var/www/html
      - ./customapps:/var/www/html/custom_apps 
      # - ../datasys/nextcl-1500/:/var/www/html
    # networks:
      # - redisnet
      # - dbnet
    # environment:
        # - VIRTUAL_HOST=nc1500-104-193-61-58.nip.io
        # - LETSENCRYPT_HOST=nc1500-104-193-61-58.nip.io
        # - VIRTUAL_PORT=80
        # - LETSENCRYPT_EMAIL=dgleba@gmail.com
        # https://github.com/nextcloud/docker/issues/593 mysql_pass is not in docs for example.
        # labels:
        #   # caddy-gen info..
        #   - "virtual.host=nc.dg24.tk nc-108-168-7-24.nip.io"
        #   - "virtual.port=80"
        #   - "virtual.tls-email=dgleba@gmail.com" # set to valid email to activate SSL
        #   - "virtual.websockets" # enable websocket passthrough
    logging:
      driver: "json-file"
      options:
        max-size: "250k"
        max-file: "100"

  db:      
    image: mariadb:11.6
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    env_file: .env
    ports:
      - "6307:3306"
    volumes:
      - db_data:/var/lib/mysql
      #- ../sysdata/maria/:/var/lib/mysql/ # folder for mysql's internal data files.
      # - .:/root # folder for scripts, etc.
      # - ../data/maria429/:/home # folder for exported data, etc.
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "50"
    # networks:
      # - sister
      # - dbnet

  redis:
    image: redis:alpine
    restart: always
    # networks:
      # - redisnet
    expose:
      - 6379
      
  adminer:
    # http://192.168.88.103:8089
    image: adminer:5
    restart: always
    ports:
      - 8089:8080
    # networks:
      # - sister
    #   labels:
    #     # caddy-gen info..  t.dg24.tk t.david23.tk
    #     - "virtual.host=admr.dg24.tk"
    #     - "virtual.port=8080"
    #     - "virtual.tls-email=dgleba@gmail.com" # set to valid email to activate SSL
    #     - "virtual.websockets" # enable websocket passthrough

volumes:
  db_data:
  nc_data:
networks:
  dbnet:
  redisnet:

# networks:
  # sister:
    # name: sister
      # external:true
