# jupyterlab

version: "3.6"

services:

  jplab:
    # http://10.4.1.231:18888  lab?token=   930f63f2611d3db4ecaaab02e60a6e28129564a566b7445a
    # http://10.4.1.231:18888/  lab?token=22269671f1c0ef04859033cd7ad6c03bb573a609db6e3a9a
jpla
    image: quay.io/jupyter/datascience-notebook:lab-4.0.8
    ports:
      - "18889:8888"
    working_dir: /home/jovyan
    env_file:
      - ./.env
    volumes:
      - ./data/jlab:/home/jovjan
      - /etc/localtime:/etc/localtime:ro
    #entrypoint: bash -c 'jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/home --allow-root'
    restart: always
    user: root  


