#version: '3.6'

services:
  nodejs:
  # http://192.168.88.103:14808
    working_dir: /app
    image: node:20-alpine
    # build:
      # context: ./nodeapp
      # dockerfile: Dockerfile
    # image: nodejs
    # container_name: nodejs
    env_file: .env
    environment:
      - MONGO_HOSTNAME=dbxx 
    expose: 
      - 8080
    ports:
      - "14808:8080"
    volumes:
      - ./express-master:/app
      # - ./nodeapp:/app 
      # - node_modules:/home/sysdata/node_modules
    # command: ./wait-for.sh db:27017 -- /home/sysdata/node_modules/.bin/nodemon app.js
    command: npm start

  # mongodb:
  #   image: mongo:4.2-bionic
  #   container_name: db
  #   env_file: .env
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
  #     - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
  #   volumes:  
  #     - dbdata:/data/db   

# volumes:
  # dbdata:
  # node_modules:      
