
services:

  redis:
    # http://   10.99.98.69
    image: redis:8-alpine
    restart: always
    ports:
      - '6379:6379'
    # command: redis-server --save 20 1 --loglevel warning --requirepass pm128rd
    # command: ["redis-server", "--appendonly", "yes"]
    command: redis-server --save 20 1 --loglevel warning 
    volumes:
      - rediscache:/data
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"

volumes:
  rediscache:
    driver: local
