# Generated by Django 4.1.7 on 2026-01-10 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogappm2m', '0002_posttbl_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttbl',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttbl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttbl',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='posttbl',
            name='postedfrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postedfrom', to='blogappm2m.postedfromtbl'),
        ),
        migrations.AlterField(
            model_name='posttbl',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='blogappm2m.tagtbl'),
        ),
        migrations.AlterField(
            model_name='posttbl',
            name='title',
            field=models.CharField(blank=True, max_length=302, null=True),
        ),
        migrations.AlterField(
            model_name='posttbl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
