version: '3'

services:
  pgedge-n1:
    hostname: n1
    build:
      context: "."
      dockerfile: Dockerfile.el9
    environment:
      - NODE=n1
    ports:
      - '15432:5432'
    volumes:
      - 'n1:/data'

  pgedge-n2:
    hostname: n2
    build:
      context: "."
      dockerfile: Dockerfile.el9
    environment:
      - NODE=n2
    ports:
      - '15433:5432'
    volumes:
      - 'n2:/data'

volumes:
  n1:
    driver: local
  n2:
    driver: local
