source:
  db_conn:
    host: ${MYSQL_HOST}
    port: ${MYSQL_PORT}
    user: ${MYSQL_USER}
    passwd: ${MYSQL_PASSWORD}
    charset: utf8
    connect_timeout: 10

target:
  db_conn:
    host: ${POSTGRES_HOST}
    port: 5432
    user: ${POSTGRES_USER}
    passwd: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DB}

replica:
  batch_size: 10000
  limit_tables: []
  limit_schemas: []
  skip_tables: []
  skip_schemas: []


# environment:
  # MYSQL_HOST: ${MYSQL_HOST}
  # MYSQL_PORT: 3306
  # MYSQL_USER: ${MYSQL_ROOT_USER}
  # MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  # PG_HOST: ${POSTGRES_HOST}
  # PG_PORT: 5432
  # PG_USER: ${POSTGRES_USER}
  # PG_PASSWORD: ${POSTGRES_PASSWORD}
  # PG_DATABASE: ${POSTGRES_DB}